name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: arch -x86_64 pod install
    - name: Build
      run: xcodebuild -workspace SNASA.xcworkspace -scheme SNASA -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14'
    - name: Test
      run: xcodebuild test -scheme SNASA -project SNASA.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' 
