name: CI-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

    
jobs:
  test:
    name: Test
    runs-on: macos-13
    strategy:
        matrix: 
          destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project SNASA.xcodeproj -scheme SNASA -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project SNASA.xcodeproj -scheme SNASA -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
